### ISSUE TITLE
More details?

### ISSUE THREAD

**Issue by kingthorin** [jamesjardine/juiceshoproutes#1]
https://github.com/jamesjardine/juiceshoproutes#use

@jamesjardine is building the jar as simple as?
`jar cf juiceshoproutes.jar juiceshoproutes/src/burp/*.*`

Can you add a screenshot of the output to the README.md?

**Comment by jamesjardine** [comment]
There are really two steps I took to build the jar. The first step was to compile the Java Files.  This is done using the javac command.  For example, if I wanted to compile the classes into a test output folder, I might create a folder named testoutput  then run the javac command:

javac -d testoutput/ juiceshoproutes/src/burp/*.java

When you cd into testoutput you should see a folder named burp. In that folder are the class files. 

Now, to turn this into a jar file, make sure you are in the testoutput folder (not in the burp folder) and run:

jar cf juiceshoproutes.jar burp

You do not want to run this from within the burp folder as it will cause an error saying it can't find the entry point when you install it into burp.

**Comment by jamesjardine** [comment]
I did add the compiled jar file under a beta release.

**Comment by kingthorin** [comment]
Thanks!
https://github.com/jamesjardine/juiceshoproutes/releases/tag/v1.0-beta.1

**Comment by kingthorin** [comment]
@jamesjardine answered my questions. It would still be great if the README had a screenshot but that's pretty minor. With the provided details users can check it out for themselves.
